replicaCount: 2
image:
  repository: ghcr.io/team-deepiri/deepiri-flint
  tag: "0.3.0"
  pullPolicy: IfNotPresent
service:
  adminPort: 9108
env:
  FLINT_SUGAR_GLIDER_URL: http://synapse-sidecar:8081
  FLINT_CONSUMER_GROUP: flint-workers
  FLINT_DRY_RUN: "false"
  FLINT_LOG_LEVEL: info
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 500m
    memory: 256Mi
